os:
  - osx

cache:
  directories:
  - $HOME/.electron

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - source ~/.bashrc
  - nvm install 6.1.0
  - nvm use 6.1.0
  - npm i -g npm
  - rm -rf node_modules
  - npm install

branches:
  except:
    - website

script:
  - npm run test
  - npm run test-unit
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./sig/import.sh && npm run make:darwin; fi
